### ISSUE TITLE
Free Shipping Issue

### ISSUE THREAD

**Issue by GoTeamScotch** [academe/wc-multiple-packages#13]
When using a free shipping coupon, the checkout page does not show them the Free Shipping method unless the page is refreshed manually.

A few of my customers were confused by this and ended up paying for shipping when they shouldn't have.

**Comment by GoTeamScotch** [comment]
Work-around:
In file woocommerce\assets\js\frontend\checkout.js, locate wc_checkout_coupons (line 378 for me) and scroll down to where the ajax call's success function is defined. After

```
$( document.body ).trigger( 'update_checkout' );
```

simply add

```
location.reload();
```

This will make the page refresh itself after a coupon is added. Do the same thing for remove_coupon. Add the reload command after 

```
$( 'form.checkout_coupon' ).find( 'input[name="coupon_code"]' ).val( '' );
```

in the ajax call.

**Comment by judgej** [comment]
Is there any way that could be added without hacking the core WC? I'm wondering if another function can be bound to the `update_checkout` event to reload the page, or part of the page? There is a binding here:

https://github.com/woothemes/woocommerce/blob/f6526d72a72e3e2b110ed6c0f7b18329239c6667/assets/js/frontend/checkout.js#L18

``` php
$( document.body ).bind( 'update_checkout', this.update_checkout );
```

I'm not familiar with these triggers and whether multiple functions can be bound to them - I'm assuming they can. It's just a possible way to get it into this plugin rather than updating core WC each time it gets updated.

**Comment by judgej** [comment]
Arguably it is a bug in WC and perhaps should be raised there. The multiple package order page is entirely generated and displayed by WC - this plugin only tells WC how to group the order lines into packages, and WC does the rest.

**Comment by GoTeamScotch** [comment]
Sorry, I just tested again on a fresh WP installation and couldn't replicate the problem so it's on my end somewhere.
