### ISSUE TITLE
Duplicated - Calculate Shipping Button

### ISSUE THREAD

**Issue by quasel** [academe/wc-multiple-packages#7]
Did just a quick Test with your plugin using Stirefront as theme:
don't know who's fault this is ;) 

Result: 
![woo-packages](https://cloud.githubusercontent.com/assets/9464217/9135940/c04dbeac-3d12-11e5-92ea-249276a405de.jpg)

**Comment by judgej** [comment]
Happens on Woo/Canvas and the stock WP theme too. I'm not sure where it is being generated. It should certainly only appear one, since although there are multiple shipping _methods_, they should all be going to the same destination.

It would be interesting to see how a plugin that allows orders to be split and shipped to multiple locations interacts with this (for a rainy day).

**Comment by judgej** [comment]
If we can find any other plugin that splits orders up into multiple packages (a reseller plugin maybe) we can see how that handles it.

**Comment by judgej** [comment]
Quick question: is that list of packages in a widget in the side bar? If so, which widget is it?

The cart page also has "calculate shipping" links under each package. I suspect this is just going to be the way WC works, and may only be fixable using theme template overrides.

**Comment by judgej** [comment]
The standard WC "cart" widget does not reference or attempt to display the packages at all. It just lists the products with an indicative cost, with no shipping costs added. That makes more sense to me.

**Comment by avishai** [comment]
On the latest WooCommerce and WC Vendors, the calculate shipping widget is displaying only on the first shipping line.
