### ISSUE TITLE
_order_line_ids  - Vote for array ;) 

### ISSUE THREAD

**Issue by quasel** [academe/wc-multiple-packages#8]
> It will also build a custom meta field "_order_line_ids" on each shipping line, pointing to the IDs of the
> item lines that it shipped. At the moment this a bar-separated list (e.g. 1|2|3) but may change to an array.

my opinion - just do it :P

**Comment by judgej** [comment]
The method that the Woo API functions where using to fetch the attributes of the order lines assume the values are strings, so I was getting a JSON-encoded string instead of a real string in the API data. I just switched to the bar-separators quickly so I could move on, but yes, will come back to it, perhaps including a WC ticket to fix the underlying problem.
